### PR TITLE
[Chore] Docker-compose refresh

### PR DESCRIPTION
**Pull request by anibalsolon**
As promised, here is the update for the docker-compose configuration! 🙃 
It comprises:
1. Linking out the Mongo instance, so as to be able to connect and query it
2. Setting it to build when the service image does not exist (with `build: .`)
3. Linking out the websocket port
4. Keeping the node_modules folder generated in the Dockerfile inside the container, instead of mounting from the host
5. Move docker-compose to root, so people know that this project supports being run by it
6. Upgrade node version used by the container: I've updated the version because there were some libraries that do not build during `npm install`. But it would be better to reflect production, which node version is used in the servers?

One open question I have would be how to deal with the configuration files: would it be better if they were merged into one single configuration file?

- [ ] Run `npm test` successfully. 
- [ ] Run `npm run mocha`successfully.

- [ ] `test_screenshots` generates the same test pictures in `test` as there were in `test/reference` and does not show any errors

- [ ] I implemented tests for the new changes OR
- [x] These changes do not require tests because they are for the development workflow

- [ ] These changes fix #__ (github issue number if applicable).

### CODE REVIEW

**Review by katjaq — APPROVED** [review]
\\\ö// Thank you so much! 😃 That's awesome!
Yes, we will look into updating the node version on the server as well (it's not thaaat old, but can have another update)
If it is in one file or several files – I think we can follow your advice 🙃

Are there any changes we should make in the Readme file for this docker compose update @anibalsolon ?

**Comment by anibalsolon** [comment]
Thank you! 🚀 Yes- I've updated the instructions on README.md, just some tiny details 🙃

**Review by katjaq — APPROVED** [review]
Great ! :) Thank you for updating the ReadMe :)

**Comment by r03ert0** [comment]
thank you so much for this @anibalsolon !!! \ö/ 🚀

**Pull request merged**
