### PR TITLE
[WIP] More permission tests

### PR DESCRIPTION
**Pull request by dhovart**
Almost there, but I need to correct two things:

- the percentage of pixels that are different is too high due to a new link in the header ("log in locally")
- I've removed the `process.exit(0)` in `runner.js` that was dumb because we want to return an error exit code if some tests fail. But then the tests are then still hanging, I suspect that something is not properly closed like a connection to mongo or something like that. Haven't found the culprit. @ntraut an idea ?

### CODE REVIEW

**Comment by dhovart** [comment]
Sorry for the force-push, I had to rebase master on top because of conflicts

**Comment by ntraut** [comment]
we have the same issue with `npm run mocha` once we remove the `--exit` argument. i'm trying to see what happens with [why-is-node-running](https://github.com/mafintosh/why-is-node-running) but it's not working very well for me, maybe because of my system...

**Comment by ntraut** [comment]
it is very unclear to me what is run when doing `npm run mocha`, do you have an idea on that?
i see that the `--exit` argument is necessary since your commit 05f0ab1807bd6b3d7b5dc16af0457a390ddc3d83, because you modified the file `test/mocha.test.util.js`. but this file doesn't seem useful for the tests run by `npm run mocha` but are for the e2e tests, is it a bug that it is sourced in this case?

**Comment by dhovart** [comment]
@ntraut  `npm run mocha` exits without issue for me. I don't know how useful these tests are - they seem to be testing that the tile system is working correctly.

**Comment by dhovart** [comment]
No, we should find a way to find what's the issue. I remember always having to exit these by hand...
With --exit it's working but I'm not comfortable having "dirty" tests that don't clean after themselves, it could impact the results. I've tried to debug them but still haven't found out the reason.

**Comment by ntraut** [comment]
in `mocha.test.util.js` the two lines which cause node to be hanging are `const db = monk(process.env.MONGODB_TEST);` and `const {server} = require('../app/app');` so we would have to close both the db and the server to avoid the force exit.

**Comment by dhovart** [comment]
Yes, this is what is being done [here](https://github.com/neuroanatomy/microdraw/pull/54/files#diff-2e68fa4c18e14d442ce746d442028ddc617db0af18a17d7f110db8bd2b451108R27)

**Comment by ntraut** [comment]
i'm not sure but it could be that the nwl module creates a new mongo connection when initializing the mongo store instead of using the existing one, so it is not closed despite of closing the other mongodb connection:
https://stackoverflow.com/questions/67297704/connect-mongo-package-with-jest-leads-to-error-jest-did-not-exit-one-second-aft

**Comment by dhovart** [comment]
Yes, the issue comes from the NWL package, might have to reuse the existing connection indeed.

**Comment by dhovart** [comment]
So, I'm reusing the mongo db and it seems to be closing fine but the tests are still hanging. Using [this method](https://gist.github.com/subfuzion/54a9413d02c6d9ba223076bebd49e38f) I can see that the server is still active:
```
  13   │ Type: TCPSERVERWRAP
  14   │ Error
  15   │     at AsyncHook.init (test/async-dump.js:12:62)
  16   │     at TCP.emitInitNative (node:internal/async_hooks:204:43)
  17   │     at createServerHandle (node:net:1230:14)
  18   │     at Server.setupListenHandle [as _listen2] (node:net:1273:14)
  19   │     at listenInCluster (node:net:1354:12)
  20   │     at Server.listen (node:net:1441:7)
  21   │     at Object.<anonymous> (app/app.js:68:8)
  22   │     at Module._compile (node:internal/modules/cjs/loader:1108:14)
  23   │     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
  24   │     at Module.load (node:internal/modules/cjs/loader:988:32)
  25   │     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
  26   │     at Module.require (node:internal/modules/cjs/loader:1012:19)
  27   │     at require (node:internal/modules/cjs/helpers:93:18)
  28   │     at Object.initResources (test/mocha.test.util.js:11:46)
  29   │     at Context.<anonymous> (test/e2e/runner.js:6:5)
  30   │     at processImmediate (node:internal/timers:464:21)
```
I've tried using http-terminator, but to no avail. So I'll just push my changes related to mongo and keep the `--exit` argument there for now if you're ok with it, because there's only that much time I can give to this issue for now...

**Comment by ntraut** [comment]
OK let's keep this aside, we will try to fix this specific issue later.

**Comment by ntraut** [comment]
I was able to fix the hanging problem by reusing the mongodb connection from monk when initializing the mongo store for the express sessions, but i had to do modifications both in nwl and microdraw so i think i should make separate pr for this.

for me the problem which remains is why `test/mocha.test.util.js` is run when doing `npm run mocha`? this script should only be used in e2e tests.

**Comment by dhovart** [comment]
Feel free to make a PR !
Per the cli documentaiton (`npm run mocha help`) it seems to be loaded just because it has `test` in its name.

```
Positional Arguments
  spec  One or more files, directories, or globs to test
                                                     [array] [default: ["test"]]
```

**Comment by dhovart** [comment]
…or maybe rather because it is in the directory `test` ?…

**Comment by ntraut** [comment]
yes apparently by default mocha run all js files inside the test directory whatever their names but not in the sub-directories. A solution would be to put `mocha.test.util.js` in another directory but maybe better would to specify the path which is run when doing `npm run mocha`: `test/mocha.test.js`

**Review by katjaq — APPROVED** [review]
That looks great! Thank you for setting up the login locally option, and updating all screenshots to the new login corner and the disconnected chat. 

will merge! 🌟

**Comment by ntraut** [comment]
We did not check the screenshot updates. Those two reference screenshots are now incorrect because of the save bug:
test/reference-screenshots/draw.04.cat-triangle-reload.png
test/reference-screenshots/multiple.05.page1-reload.png

We will have to reupload them once the bug will be fixed.

**Pull request merged**
